// packages/demo/src/integrations/demo.vue
<template>
  Simple date time:
  <div class="timescape-root" :ref="registerRoot()">
    <input :ref="registerElement('years')" class="timescape-input" />
    <span class="separator">/</span>
    <input :ref="registerElement('months')" class="timescape-input" />
    <span class="separator">/</span>
    <input :ref="registerElement('days')" class="timescape-input" />
    <span class="separator">&nbsp;</span>
    <input :ref="registerElement('hours')" class="timescape-input" />
    <span class="separator">:</span>
    <input :ref="registerElement('minutes')" class="timescape-input" />
    <span class="separator">:</span>
    <input :ref="registerElement('seconds')" class="timescape-input" />
  </div>
  <br />
  Range:
  <div class="timescape-root" :ref="registerRangeRoot()">
    <input class="timescape-input" :ref="from.registerElement('years')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="from.registerElement('months')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="from.registerElement('days')" />
    <span class="separator">–</span>
    <input class="timescape-input" :ref="to.registerElement('years')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="to.registerElement('months')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="to.registerElement('days')" />
  </div>
</template>

<script lang="ts" setup>
import { useTimescape, useTimescapeRange } from "timescape/vue";
import { watchEffect } from "vue";

const Y2K38 = new Date((2 ** 31 - 1) * 1000);

const { registerElement, registerRoot, options } = useTimescape({
  date: new Date(),
  maxDate: Y2K38,
});

watchEffect(() => {
  console.log("Date changed to", options.value.date);
});

const { from, to, registerRangeRoot } = useTimescapeRange({
  from: { date: new Date() },
  to: { date: new Date("2024-12-12") },
});
</script>

// packages/demo/src/integrations/demo.react.tsx
import { useTimescape, useTimescapeRange } from 'timescape/react'
import { useEffect } from 'react'

export const ReactDemo = () => {
  const { getRootProps, getInputProps, options } = useTimescape({
    date: new Date(),
  })

  const {
    getRootProps: getRangeRootProps,
    from,
    to,
  } = useTimescapeRange({
    from: {
      date: new Date(),
      onChangeDate: () => {
        console.log('from date changed')
      },
    },
    to: {
      date: new Date('2024-12-31'),
      onChangeDate: () => {
        console.log('to date changed')
      },
    },
  })

  useEffect(() => {
    console.log('Date changed', options.date)
  }, [options.date])

  return (
    <div>
      Simple date time:
      <div className="timescape-root" {...getRootProps()}>
        <input
          className="timescape-input"
          {...getInputProps('days')}
          placeholder="dd"
        />
        <span className="separator">/</span>
        <input
          className="timescape-input"
          {...getInputProps('months')}
          placeholder="mm"
        />
        <span className="separator">/</span>
        <input
          className="timescape-input"
          {...getInputProps('years')}
          placeholder="yyyy"
        />
        <span className="separator">&nbsp;</span>
        <input
          className="timescape-input"
          {...getInputProps('hours')}
          placeholder="hh"
        />
        <span className="separator">:</span>
        <input
          className="timescape-input"
          {...getInputProps('minutes')}
          placeholder="mm"
          step={10}
        />
        <span className="separator">:</span>
        <input
          className="timescape-input"
          {...getInputProps('seconds')}
          placeholder="mm"
        />
      </div>
      <br />
      Range:
      <div>
        <div className="timescape-root" {...getRangeRootProps()}>
          <input className="timescape-input" {...from.getInputProps('years')} />
          <span className="separator">/</span>
          <input
            className="timescape-input"
            {...from.getInputProps('months')}
          />
          <span className="separator">/</span>
          <input className="timescape-input" {...from.getInputProps('days')} />
          <span className="separator">&ndash;</span>
          <input className="timescape-input" {...to.getInputProps('years')} />
          <span className="separator">/</span>
          <input className="timescape-input" {...to.getInputProps('months')} />
          <span className="separator">/</span>
          <input className="timescape-input" {...to.getInputProps('days')} />
        </div>
      </div>
    </div>
  )
}
