// packages/demo/src/integrations/demo.svelte
<script lang="ts">
import { createTimescape, createTimescapeRange } from "timescape/svelte";
import "../IntegrationDemo.css";
import { writable } from "svelte/store";

const date = writable<Date | null>(window.date ?? new Date());

const { inputProps, rootProps } = createTimescape({
  date,
  onDateChange: (newDate) => {
    console.log("Date changed to", newDate?.toLocaleString());
    date.set(newDate);
  },
});

const {
  from,
  to,
  rootProps: rangeRootProps,
} = createTimescapeRange({
  from: { defaultDate: new Date() },
  to: { defaultDate: new Date(Date.now() + 31536e6 * 3) }, // 3 years from now
});
</script>

  Simple date time:
  <div class="timescape-root" use:rootProps>
    <input use:inputProps={'years'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:inputProps={'months'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:inputProps={'days'} class="timescape-input" />
    <span class="separator">&nbsp;</span>
    <input use:inputProps={'hours'} class="timescape-input" />
    <span class="separator">:</span>
    <input use:inputProps={'minutes'} class="timescape-input" />
    <span class="separator">:</span>
    <input use:inputProps={'seconds'} class="timescape-input" />
  </div>
  <br />
  Range:
  <div class="timescape-root" use:rangeRootProps>
    <input use:from.inputProps={'years'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:from.inputProps={'months'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:from.inputProps={'days'} class="timescape-input" />
    <span class="separator">&ndash;</span>
    <input use:to.inputProps={'years'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:to.inputProps={'months'} class="timescape-input" />
    <span class="separator">/</span>
    <input use:to.inputProps={'days'} class="timescape-input" />
  </div>
  <div id="output" style="display: none">
    {$date?.toISOString()}
  </div>

// packages/demo/src/integrations/demo.vue
<template>
  <div>
    Simple date time:
    <div class="timescape-root" :ref="registerRoot()">
      <input :ref="registerElement('years')" class="timescape-input" />
      <span class="separator">/</span>
      <input :ref="registerElement('months')" class="timescape-input" />
      <span class="separator">/</span>
      <input :ref="registerElement('days')" class="timescape-input" />
      <span class="separator">&nbsp;</span>
      <input :ref="registerElement('hours')" class="timescape-input" />
      <span class="separator">:</span>
      <input :ref="registerElement('minutes')" class="timescape-input" />
      <span class="separator">:</span>
      <input :ref="registerElement('seconds')" class="timescape-input" />
    </div>
    <br />
    Range:
  <div class="timescape-root" :ref="registerRangeRoot()">
    <input class="timescape-input" :ref="from.registerElement('years')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="from.registerElement('months')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="from.registerElement('days')" />
    <span class="separator">–</span>
    <input class="timescape-input" :ref="to.registerElement('years')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="to.registerElement('months')" />
    <span class="separator">/</span>
    <input class="timescape-input" :ref="to.registerElement('days')" />
  </div>
  </div>
  <div id="output" style="display: none">
    {{ date?.toISOString() }}
  </div>
</template>

<script lang="ts" setup>
import { useTimescape, useTimescapeRange } from "timescape/vue";
import { ref } from "vue";

const date = ref<Date | null>(window.date ?? new Date());

const { registerElement, registerRoot } = useTimescape({
  date,
  onDateChange: (newDate) => {
    console.log("Date changed to", newDate);
    date.value = newDate;
  },
});

const { from, to, registerRangeRoot } = useTimescapeRange({
  from: { defaultDate: new Date() },
  to: { defaultDate: new Date(Date.now() + 31536e6 * 3) }, // 3 years from now
});
</script>
